name: .NET Framework Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore DevToolBox.sln

    - name: Build the project
      run: msbuild DevToolBox.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Zip Artifacts
      run: Compress-Archive -Path DevToolBox\bin\Release\* -DestinationPath Release.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: Release.zip